CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    display_name TEXT,
    intent TEXT,
    email_verified INTEGER DEFAULT 0,
    is_admin INTEGER DEFAULT 0,
    created_at TEXT NOT NULL,
    auth_provider TEXT DEFAULT 'email',
    last_login TEXT
);

CREATE INDEX IF NOT EXISTS idx_users_created
ON users(created_at);

CREATE INDEX IF NOT EXISTS idx_users_email
ON users(email);


CREATE TABLE IF NOT EXISTS user_profile (
    user_id INTEGER PRIMARY KEY,
    goals TEXT,
    CONSTRAINT fk_user_profile_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS email_otps (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    otp TEXT NOT NULL,
    expires_at BIGINT NOT NULL
);


CREATE TABLE IF NOT EXISTS admin_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id INTEGER,
    action TEXT,
    target_user_id INTEGER,
    timestamp TEXT,
    CONSTRAINT fk_admin_logs_admin
        FOREIGN KEY (admin_id)
        REFERENCES users(id)
        ON DELETE SET NULL,
    CONSTRAINT fk_admin_logs_target
        FOREIGN KEY (target_user_id)
        REFERENCES users(id)
        ON DELETE SET NULL
);


CREATE TABLE IF NOT EXISTS conversations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    history TEXT,
    created_at TEXT,
    user_id INTEGER,
    CONSTRAINT fk_conversations_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_conv_user
ON conversations(user_id);


CREATE TABLE IF NOT EXISTS memories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conv_id INTEGER NOT NULL,
    summary TEXT,
    updated_at TEXT,
    user_id INTEGER,
    CONSTRAINT fk_memories_conversation
        FOREIGN KEY (conv_id)
        REFERENCES conversations(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_memories_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS journal_entries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TEXT,
    content TEXT,
    user_id INTEGER,
    title TEXT,
    mood TEXT,
    tags TEXT,
    CONSTRAINT fk_journal_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_journal_user
ON journal_entries(user_id);


CREATE TABLE IF NOT EXISTS mood_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mood TEXT NOT NULL,
    message TEXT,
    date TEXT NOT NULL,
    user_id INTEGER,
    CONSTRAINT fk_mood_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_mood_user
ON mood_logs(user_id);